### ISSUE TITLE
turn on/off both a fan and a thermostat  

### ISSUE THREAD

**Issue by sgrizzi** [sinricpro/esp8266-esp32-sdk#149]
Hi,
in order to support a Daikin airco, I need to make use of both the functionalities of a fan and those of a thermostat.
Specifically, if I turn on the "fan", then the "thermostat" should turn on as well and viceversa.

Within the onPowerStateFan routine I use the .sendPowerStateEvent(state) command towards the thermostat and vice-versa from the thermostat to the fan.
Everything seems to work fine though I notice a relatively long delay (15..30s) between the direct action (i.e. the one that triggers the  onPowerStateFan callback and the action driven by the .sendPowerStateEvent(state) command.
Is this expected/correct?
Rgds, Gabriele

**Comment by sivar2311** [comment]
Usually this should be very fast - can you check serial log on this?

Did you use the new custom device feature for this?

**Comment by sgrizzi** [comment]
Hi Boris,

I made some additional checks.

The reaction of a thermostat, for example is very fast indeed if I turn on/off the corresponding fan using the SinricPro app. The delay is introduced when I drive the fan/thermo from Alexa: the “direct” action is very fast, while the “consequent” one is delayed by 15-30s.

 

No, I did not use the new custom feature – I need first to learn how to use this new possibility. Can you point me to any tutorial? Doc, or example?

Rgds, Gabriele

**Comment by sivar2311** [comment]
Tutorial is not ready yet (i am not a good youtuber)
On the mainpage (sinric.pro) you can see a gif animation 
- On the left side menu go to Device Templates
- Add a new device template (same like adding a device)
- Enter basic infos (1/2)
- Customize capabilities (2/2) -> it's like building blocks
- Save template
- Create a new device - choose your template as device type
- In "Devices" you can use the (newly introduced) codegenerator
- Download the files, fill in wifi credentials and modify callbacks etc to your needs
- Done ;)

**Comment by sgrizzi** [comment]
Hi Boris, thanks for the useful mini-tutorial! I will definitely have a go.

Meanwhile I am having additional problems with the interfacing of the Thermostat with Alexa.
Alexa will "read" the proper status from Sinric Thermostat, but has problems "setting" values into Sinric device.
Precisely, using Alexa:
- I can turn on/off the Thermostat. I can see the serial output of the ESP32 doing what expected
- I can read Sinric Thermostat local temperature
- when I try and set a target temperature, Alexa pauses a few seconds and then will say "I have problems connecting". Meanwhile, checking the ESP32 serial output, I can see that neither onTargetTemperature nor onAdjustTargetTemperature callbacks are triggered.

The same actions triggered using Sinric portal or Sinric app do work fine and do show up on the serial port.
The activity log does not show anything strange, errors or other.
For your reference, I have no problems with Alexa and the interface to Sinric fan device.

Can you give me some hints on where to look for possible bugs?  
Best regards, Gabriele

**Comment by sivar2311** [comment]
Sounds that's not an issue related to the ESP.
Please re-link your Alexa skill.

btw: "I have problems connecting" is new to me.
If there is a problem, this is usually something like "The device is not responding"

**Comment by sgrizzi** [comment]
Hi Boris,

I un-linked and re-linked SinricPro skill but it did not solve the problem.

I can still switch on/off the thermostat, read its temperature data, but I cannot set the temperature.

The weird voice message is coming from my Echo 8 device. When I try with my iphone, I get a “server is unresponsive” message for a couple of seconds. I managed to capture this – see below.

I confirm that the thermostat interface works well with Sinric app and portal.

 

This is the serial output of the ESP32. In red bold the two on/off events triggered by Alexa. In between I tried to raise the temperature and got the “server unresponsive message”.

 

11:23:55.501 -> *****

11:23:55.501 -> airco 601d7561c1d53d01a1f54089 temperature 22.000000 humidity 35.000000

11:23:55.501 -> airco 603f62b75af47973178539b7 temperature 22.000000 humidity 35.000000

11:23:55.536 -> airco 603f62d25af47973178539bc temperature 22.000000 humidity 40.000000

11:23:55.536 -> airco 603f62eafbb434731e28915e temperature 23.000000 humidity 30.000000

11:23:55.574 -> Temperature: 12.8 Celsius    Humidity: 49.8%

11:24:24.335 -> Thermostat 601d7561c1d53d01a1f54089 turned on

11:24:49.217 -> Monitra Advertised Device found: Name: , Address: 00:0b:57:f1:03:03, manufacturer data: 3e0301040044301800f80105

11:24:49.217 -> light f8 01 

11:24:49.217 -> temp 05 05 

11:24:49.217 -> 

11:25:55.559 -> Temperature: 12.9 Celsius    Humidity: 49.7%

11:26:39.203 -> Thermostat 601d7561c1d53d01a1f54089 turned off

 

This is the same sequence triggered by the Sinric app

 

10:33:10.239 -> Thermostat 601d7561c1d53d01a1f54089 turned on

10:33:43.764 -> *****

10:33:43.764 -> airco 601d7561c1d53d01a1f54089 temperature 22.000000 humidity 35.000000

10:33:43.764 -> airco 603f62b75af47973178539b7 temperature 22.000000 humidity 30.000000

10:33:43.764 -> airco 603f62d25af47973178539bc temperature 22.000000 humidity 35.000000

10:33:43.764 -> airco 603f62eafbb434731e28915e temperature 23.000000 humidity 30.000000

10:33:43.802 -> Temperature: 12.2 Celsius    Humidity: 50.6%

10:33:54.425 -> Monitra Advertised Device found: Name: , Address: 00:0b:57:f1:03:03, manufacturer data: 3e0301040011301800f801bd

10:33:54.425 -> light f8 01 

10:33:54.425 -> temp bd 04 

10:33:54.425 -> 

10:34:05.019 -> Thermostat 601d7561c1d53d01a1f54089 set temperature to 27.000000

10:34:21.298 -> Thermostat 601d7561c1d53d01a1f54089 set temperature to 26.000000

10:34:27.149 -> Thermostat 601d7561c1d53d01a1f54089 turned off

 

(The block underlined blue is, just as an example, the sequence of updates of local temperature & humidity which is sent to Alexa with a set of sendTemperatureEvent() commands, and this does also work fine. I am actually using 4 thermostats, but they do all behave the same…)

 

No problems at all when using the fan with Alexa: on/off/speed settings do work fine also with Alexa.

 

Would you have any other suggestion what to check? Unfortunately the Sinric portal log is not logging events coming in from Alexa

Best regards, Gabriele

**Comment by sivar2311** [comment]
Ok, we will check this 

Sidenote: There are no blue or red lines in your github-comments. 
Maybe the reason is because you answer via e-mail and not using [github issue page](https://github.com/sinricpro/esp8266-esp32-sdk/issues/149)?

**Comment by sgrizzi** [comment]
Indeed, I used a normal e.mail... and formatting is all gone...
Herebelow the relevant part of the serial print with bold and italic parts (colors are not available ?)
I also attached the iphone screen shot, which was also missing.
As an additional note, I am still using SinricPro SDK version 2.7.6 because another library (Autoconnect) is not compatible with SSL. Did you change anything in the library that might be connected to this issue?
Rgds, Gabriele
  

This is the serial output of the ESP32. In **bold** the two on/off events triggered by Alexa. In between, I tried to raise the temperature and got the “server unresponsive message”.

11:23:55.501 -> *****
11:23:55.501 -> airco 601d7561c1d53d01a1f54089 temperature 22.000000 humidity 35.000000
11:23:55.501 -> airco 603f62b75af47973178539b7 temperature 22.000000 humidity 35.000000
11:23:55.536 -> airco 603f62d25af47973178539bc temperature 22.000000 humidity 40.000000
11:23:55.536 -> airco 603f62eafbb434731e28915e temperature 23.000000 humidity 30.000000
11:23:55.574 -> Temperature: 12.8 Celsius    Humidity: 49.8%
**11:24:24.335 -> Thermostat 601d7561c1d53d01a1f54089 turned on**
11:24:49.217 -> Monitra Advertised Device found: Name: , Address: 00:0b:57:f1:03:03, manufacturer data: 3e0301040044301800f80105
11:24:49.217 -> light f8 01
11:24:49.217 -> temp 05 05
11:24:49.217 ->
11:25:55.559 -> Temperature: 12.9 Celsius    Humidity: 49.7%
**11:26:39.203 -> Thermostat 601d7561c1d53d01a1f54089 turned off**

This is the same sequence triggered by the Sinric app

**10:33:10.239 -> Thermostat 601d7561c1d53d01a1f54089 turned on**
10:33:43.764 -> *****
_10:33:43.764 -> airco 601d7561c1d53d01a1f54089 temperature 22.000000 humidity 35.000000
10:33:43.764 -> airco 603f62b75af47973178539b7 temperature 22.000000 humidity 30.000000
10:33:43.764 -> airco 603f62d25af47973178539bc temperature 22.000000 humidity 35.000000
10:33:43.764 -> airco 603f62eafbb434731e28915e temperature 23.000000 humidity 30.000000_
10:33:43.802 -> Temperature: 12.2 Celsius    Humidity: 50.6%
10:33:54.425 -> Monitra Advertised Device found: Name: , Address: 00:0b:57:f1:03:03, manufacturer data: 3e0301040011301800f801bd
10:33:54.425 -> light f8 01
10:33:54.425 -> temp bd 04
10:33:54.425 ->
**10:34:05.019 -> Thermostat 601d7561c1d53d01a1f54089 set temperature to 27.000000
10:34:21.298 -> Thermostat 601d7561c1d53d01a1f54089 set temperature to 26.000000
10:34:27.149 -> Thermostat 601d7561c1d53d01a1f54089 turned off**

(The block in _italic_ is, just as an example, the sequence of updates of local temperature & humidity which is sent to Alexa with a set of sendTemperatureEvent() commands, and this does also work fine. I am actually using 4 thermostats, and  they do all behave the same…)

![2021-03-04 11 25 24](https://user-images.githubusercontent.com/10333957/109971294-5f716c80-7cf6-11eb-9faa-fb5ab5b2657d.png)

**Comment by sivar2311** [comment]
> As an additional note, I am still using SinricPro SDK version 2.7.6 because another library (Autoconnect) is not compatible with SSL. Did you change anything in the library that might be connected to this issue?

Hi Gabriele,

I was able to reproduce the issue.
The issue have been located. It's a server side issue - nothing related to your ESP your sketch or SDK.
Means: Don't worry, we'll fix it ;)

What about the issue with Autoconnect & SSL? 
Maybe open an issue in Autoconnect repository?

The ESP(8266) is only to handle one SSL connection at a time.
I think the ESP32 is having the same limitation.

You can force SinricProSDK to non-ssl connection by `#define SINRICPRO_NOSSL` before including SinricPro.h.
*This will work as long as the SinricPro server accepting non-ssl connections.*

To be able to use custom devices, you must update to SinricProSDK 2.9.1

**Comment by sgrizzi** [comment]
Great news, thanks!!!

The original structure of the current sw was developed towards the end of last year for a multi-functional "push button" incorporating 18 "devices", and Autoconnect was a nice, easy way to implement ESP commissioning, a  web GUI to enter deviceIDs and a BLE mac address, and the OTA functionality.
The module using 4 thermostats, 4 fans, a motion detector and a few temperature sensors is test device, is derived from the former one.
Now, the first device will move to a PaSS implementation so we will no longer need Autoconnect additional functionalities and the second device will then also be moved to a commissioning mechanism similar to PaSS. So, trying to include SSL into Autoconnect is not very useful.

Now that I know that the program is basically working, I will focus on removing Autonnect and then upgrade the SDK.

Thanks for your very prompt support!
Rgds, Gabriele

**Comment by kakopappa** [comment]
Alexa Thermostat issue fixed. Can you please check and confirm?

**Comment by sgrizzi** [comment]
YES !!

It works !

 

Thanks a lot,

Gabriele

**Comment by kakopappa** [comment]
@sgrizzi  FYI: We have added Alexa command logs in the next release 
![image](https://user-images.githubusercontent.com/7474406/110096145-36bda580-7dd0-11eb-94b6-8a9d50a48301.png)

**Comment by sgrizzi** [comment]
Very good !!!

 

Maybe an additional suggestion would be to enable the download of the log (eg. in csv format) directly from the portal. This will make further analysis or filtering more handy.

For example, I copy and paste the information in an excel sheet, and the use the filtering options in excel to select all that is related to a specific event/device/timeframe or other.

… unless you want to add filtering possibilities directly in your portal… 😊

 

Rgds, Gabriele

**Comment by kakopappa** [comment]
Sure. Will add this to our backlog
